[WIP] Resolve category errors in spec text
tc39/proposal-regexp-unicode-property-escapes pull request #33
Opened 2017-12-01 23:01 UTC by mathiasbynens

See #12.

2017-12-03 19:32 UTC, allenwb requested changes
I want to be sure that i is very clear that we are comparing the actual source code unicode code points  to the code points of the the names in the various Unicode tables.

Also see discussion of normalization and combining characters in https://tc39.github.io/ecma262/#sec-source-text and consider if it has any implications WRT that comparison. (I don't think it does, but it's worth some thought)

2017-12-03 19:32 UTC, allenwb commented on spec.html
> +
I think you only need to define these for
UnicodePropertyNameCharacters :: ...
and 
UnicodePropertyValueCharacters :: ...

The chain rule should then apply when applying SourceText to UnicodePropertyName, UnicodePropertyValue, or LoneUnicodePropertyNameOrValue

2017-12-03 19:32 UTC, allenwb commented on spec.html
> +    It is a Syntax Error if SourceText of <emu-nt>UnicodePropertyName</emu-nt> is not a Unicode property name or property alias listed in the “Property name and aliases” column of <emu-xref href="#ta
I be a bit more explicit:
... if the sequence of Unicode code points that is  SourceText of _UnicodePropertyName_ is not identical to the code point sequence   of ...

2017-12-03 19:32 UTC, allenwb commented on spec.html
> +    It is a Syntax Error if SourceText of <emu-nt>UnicodePropertyValue</emu-nt> is not a value or value alias listed in the “Property value and aliases” column of <emu-xref href="#table-unicode-gener
see above

2017-12-03 19:32 UTC, allenwb commented on spec.html
> +    It is a Syntax Error if SourceText of <emu-nt>UnicodePropertyName</emu-nt> is a Unicode binary property or binary property alias listed in the “Property name and aliases” column of <emu-xref href
see above

2017-12-03 19:32 UTC, allenwb commented on spec.html
> +    It is a Syntax Error if SourceText of <emu-nt>UnicodePropertyValue</emu-nt> is not a value or value alias for the Unicode property or property alias SourceText of <emu-nt>UnicodePropertyName</emu
see above

2017-12-03 19:32 UTC, allenwb commented on spec.html
> +    It is a Syntax Error if SourceText of <emu-nt>LoneUnicodePropertyNameOrValue</emu-nt> is not a Unicode general category or general category alias listed in the “Property value and aliases” column
see above

2017-12-03 19:32 UTC, allenwb commented on spec.html
> +    1. Return the source text that was recognized as |UnicodePropertyName|.
I'd say:

Return the ordered List of the Unicode code points of the source text...

We're moving from the domain of the grammar to the domain of pseudo-code where  we manipulate Lists.

2017-12-03 19:32 UTC, allenwb commented on spec.html
> +    1. Assert: _p_ is a Unicode property name or property alias listed in the “Property name and aliases” column of <emu-xref href="#table-nonbinary-unicode-properties"></emu-xref> or <emu-xref href=
like static semantic rules above.  But since this is just an assert it probably is ok to say it in this sloppier (and more concise) manner

2017-12-03 19:32 UTC, allenwb commented on spec.html
> +  <p>The abstract operation UnicodeMatchProperty takes a parameter _p_ that is a List of |SourceCharacter| values and performs the following steps:</p>
...List of Unicode code points...

2017-12-03 19:32 UTC, allenwb commented on spec.html
>      1. Return _property_.
Return the List of Unicode code points of _property_.

2017-12-03 19:32 UTC, allenwb commented on spec.html
> +  <p>The abstract operation UnicodeMatchPropertyValue takes two parameters _p_ and _v_, each of which is a List of |SourceCharacter| values, and performs the following steps:</p>
...List of Unicode code points...

2017-12-03 19:32 UTC, allenwb commented on spec.html
>      1. Return _value_.
Return the List of Unicode code points of _value_.

2017-12-03 19:32 UTC, allenwb commented on spec.html
> +  1. If ! UnicodeMatchPropertyValue(`"General_Category"`, _LoneUnicodePropertyNameOrValue_) is the name of a Unicode general category or general category alias listed in the “Property value and alias
If UnicodeMatchPropertyValue(`"General_Category"`, _LoneUnicodePropertyNameOrValue_) is not identical to the code point sequence of a Unicode general category or ...

2017-12-04 00:25 UTC, mathiasbynens commented
Thanks for the detailed feedback. I’ve updated the patch. Please take another look.

> Also see discussion of normalization and combining characters in https://tc39.github.io/ecma262/#sec-source-text and consider if it has any implications WRT that comparison. (I don't think it does, but it's worth some thought)

For the record, I confirm that normalization doesn’t have any implications here. Unicode property values and their aliases are limited to the character set for [`UnicodePropertyValueCharacter`](https://tc39.github.io/proposal-regexp-unicode-property-escapes/#prod-UnicodePropertyValueCharacter) in the grammar. Unicode property names and their aliases are even more limited than that (as they cannot contain numbers).

2017-12-04 16:40 UTC, allenwb approved these changes

2017-12-04 16:57 UTC, mathiasbynens commented
Thanks, Allen!

2017-12-04 16:57 UTC, merged

2017-12-05 05:04 UTC, littledan reviewed
LGTM